name: Java CI with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read      # needed for checkout
  pages: write        # needed to publish to gh-pages
  id-token: write     # needed by deploy-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Run tests and generate Allure report
        run: |
          mvn clean test
          mvn allure:report

      - name: Publish Allure site as Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: target/site/allure-maven-plugin

  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
