name: Java CI with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven local repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build & run tests
        run: mvn clean test -Dmaven.test.failure.ignore=true

      - name: Generate Allure HTML report
        run: mvn allure:report

      - name: Upload Allure results
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: target/allure-results

      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: target/site/allure-maven-plugin

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
